/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: iwanaidris (https://sketchfab.com/iwanaidris)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cat-eye-glasses-a9e9aef9d630407f9956eca64d54719e
Title: cat-eye glasses
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

const CatEyeSunglasses = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/cat-eye_glasses.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group scale={0.1} position={[0, -0.28, 0.25]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          // material={materials.blinn2SG}
        >
          <meshPhongMaterial color="#000000" transparent opacity={0.85} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.phong1SG}
        />
      </group>
    </group>
  );
});

useGLTF.preload("/cat-eye_glasses.glb");

export default CatEyeSunglasses;
